version: '3.0'
services:
  mongo:
    image: mongo:4.0.4
    restart: unless-stopped
    ports:
      - 27017:27017
#      - 27018:27018
#      - 27019:27019
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - ./.database:/data/db

  database:
    build: .
    restart: unless-stopped
    links:
      - mongo
    ports:
      - 3000:27000
    environment:
      - MONGO_DB_ENDPOINT=mongodb://mongo:27017/users